# This is thee notes dyanamodb table
notesTablecmbx: # this is the logical name
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: notes-cmbx-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: notesId
        AttributeType: S
    KeySchema: # partition key
      - AttributeName: notesId
        KeyType: HASH


#Cognito userpool

cognitoUserPool: #Logical name
  Type: AWS::Cognito::UserPool
  Properties: 
    UserPoolName: MyNotesUp-${self:provider.stage}
    
# User pool web client
cognitoUserPoolWebClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref cognitoUserPool
    ClientName: web
    AllowedOAuthFlowsUserPoolClient: true
    SupportedIdentityProviders:
      - COGNITO
    AllowedOAuthScopes:
      - phone
      - email
      - profile
      - openid
    AllowedOAuthFlows:
      - implicit
    CallbackURLs:
      - http://localhost:3000

# Cognito userpool domain
cognitorUserPoolDomain: # Logical Name
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    Domain: cmb-${self:provider.stage}
    UserPoolId: !Ref cognitoUserPool

#Application parameters
userPoolIdParams:
  Type: AWS::SSM::Parameter
  Properties: 
    Name: /notes/${self:provider.stage}/userpoolid
    Type: String
    Value: !GetAtt cognitoUserPool.Arn
